package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFeedbackRecordModel<M extends BaseFeedbackRecordModel<M>> extends Model<M> implements IBean {

	public M setFrId(java.lang.Integer frId) {
		set("frId", frId);
		return (M)this;
	}
	
	public java.lang.Integer getFrId() {
		return getInt("frId");
	}

	public M setFrUser(java.lang.String frUser) {
		set("frUser", frUser);
		return (M)this;
	}
	
	public java.lang.String getFrUser() {
		return getStr("frUser");
	}

	public M setFrDate(java.util.Date frDate) {
		set("frDate", frDate);
		return (M)this;
	}
	
	public java.util.Date getFrDate() {
		return get("frDate");
	}

	public M setFrType(java.lang.String frType) {
		set("frType", frType);
		return (M)this;
	}
	
	public java.lang.String getFrType() {
		return getStr("frType");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

	public M setFrsize(java.lang.Integer frsize) {
		set("frsize", frsize);
		return (M)this;
	}
	
	public java.lang.Integer getFrsize() {
		return getInt("frsize");
	}

}
