package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLawStudyModel<M extends BaseLawStudyModel<M>> extends Model<M> implements IBean {

	public M setSlId(java.lang.String slId) {
		set("slId", slId);
		return (M)this;
	}
	
	public java.lang.String getSlId() {
		return getStr("slId");
	}

	public M setSlName(java.lang.String slName) {
		set("slName", slName);
		return (M)this;
	}
	
	public java.lang.String getSlName() {
		return getStr("slName");
	}

	public M setSlTitle(java.lang.String slTitle) {
		set("slTitle", slTitle);
		return (M)this;
	}
	
	public java.lang.String getSlTitle() {
		return getStr("slTitle");
	}

	public M setSlContent(java.lang.String slContent) {
		set("slContent", slContent);
		return (M)this;
	}
	
	public java.lang.String getSlContent() {
		return getStr("slContent");
	}

	public M setSlResult(java.lang.String slResult) {
		set("slResult", slResult);
		return (M)this;
	}
	
	public java.lang.String getSlResult() {
		return getStr("slResult");
	}

	public M setSlDieDate(java.lang.String slDieDate) {
		set("slDieDate", slDieDate);
		return (M)this;
	}
	
	public java.lang.String getSlDieDate() {
		return getStr("slDieDate");
	}

	public M setSlState(java.lang.String slState) {
		set("slState", slState);
		return (M)this;
	}
	
	public java.lang.String getSlState() {
		return getStr("slState");
	}

	public M setSlDate(java.lang.String slDate) {
		set("slDate", slDate);
		return (M)this;
	}
	
	public java.lang.String getSlDate() {
		return getStr("slDate");
	}

	public M setEpId(java.lang.String epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.String getEpId() {
		return getStr("epId");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

}
