package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRewardPunishModel<M extends BaseRewardPunishModel<M>> extends Model<M> implements IBean {

	public M setRpId(java.lang.Integer rpId) {
		set("rpId", rpId);
		return (M)this;
	}
	
	public java.lang.Integer getRpId() {
		return getInt("rpId");
	}

	public M setRpName(java.lang.String rpName) {
		set("rpName", rpName);
		return (M)this;
	}
	
	public java.lang.String getRpName() {
		return getStr("rpName");
	}

	public M setRpTitle(java.lang.String rpTitle) {
		set("rpTitle", rpTitle);
		return (M)this;
	}
	
	public java.lang.String getRpTitle() {
		return getStr("rpTitle");
	}

	public M setRpCreateDate(java.util.Date rpCreateDate) {
		set("rpCreateDate", rpCreateDate);
		return (M)this;
	}
	
	public java.util.Date getRpCreateDate() {
		return get("rpCreateDate");
	}

	public M setRpContent(java.lang.String rpContent) {
		set("rpContent", rpContent);
		return (M)this;
	}
	
	public java.lang.String getRpContent() {
		return getStr("rpContent");
	}

	public M setRpResult(java.lang.String rpResult) {
		set("rpResult", rpResult);
		return (M)this;
	}
	
	public java.lang.String getRpResult() {
		return getStr("rpResult");
	}

	public M setRpReciver(java.lang.String rpReciver) {
		set("rpReciver", rpReciver);
		return (M)this;
	}
	
	public java.lang.String getRpReciver() {
		return getStr("rpReciver");
	}

	public M setRpCustom(java.lang.String rpCustom) {
		set("rpCustom", rpCustom);
		return (M)this;
	}
	
	public java.lang.String getRpCustom() {
		return getStr("rpCustom");
	}

}
