package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEduplanModel<M extends BaseEduplanModel<M>> extends Model<M> implements IBean {

	public M setEpId(java.lang.String epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.String getEpId() {
		return getStr("epId");
	}

	public M setEpName(java.lang.String epName) {
		set("epName", epName);
		return (M)this;
	}
	
	public java.lang.String getEpName() {
		return getStr("epName");
	}

	public M setEpTitle(java.lang.String epTitle) {
		set("epTitle", epTitle);
		return (M)this;
	}
	
	public java.lang.String getEpTitle() {
		return getStr("epTitle");
	}

	public M setEpLawStudy(java.lang.String epLawStudy) {
		set("epLawStudy", epLawStudy);
		return (M)this;
	}
	
	public java.lang.String getEpLawStudy() {
		return getStr("epLawStudy");
	}

	public M setEpMovieWatch(java.lang.String epMovieWatch) {
		set("epMovieWatch", epMovieWatch);
		return (M)this;
	}
	
	public java.lang.String getEpMovieWatch() {
		return getStr("epMovieWatch");
	}

	public M setEpCaseRead(java.lang.String epCaseRead) {
		set("epCaseRead", epCaseRead);
		return (M)this;
	}
	
	public java.lang.String getEpCaseRead() {
		return getStr("epCaseRead");
	}

	public M setEpThinkReport(java.lang.String epThinkReport) {
		set("epThinkReport", epThinkReport);
		return (M)this;
	}
	
	public java.lang.String getEpThinkReport() {
		return getStr("epThinkReport");
	}

	public M setEpTalk(java.lang.String epTalk) {
		set("epTalk", epTalk);
		return (M)this;
	}
	
	public java.lang.String getEpTalk() {
		return getStr("epTalk");
	}

	public M setEpService(java.lang.String epService) {
		set("epService", epService);
		return (M)this;
	}
	
	public java.lang.String getEpService() {
		return getStr("epService");
	}

	public M setEpStratTime(java.util.Date epStratTime) {
		set("epStratTime", epStratTime);
		return (M)this;
	}
	
	public java.util.Date getEpStratTime() {
		return get("epStratTime");
	}

	public M setEpEndTime(java.util.Date epEndTime) {
		set("epEndTime", epEndTime);
		return (M)this;
	}
	
	public java.util.Date getEpEndTime() {
		return get("epEndTime");
	}

	public M setEpContent(java.lang.String epContent) {
		set("epContent", epContent);
		return (M)this;
	}
	
	public java.lang.String getEpContent() {
		return getStr("epContent");
	}

	public M setEpCreateDate(java.util.Date epCreateDate) {
		set("epCreateDate", epCreateDate);
		return (M)this;
	}
	
	public java.util.Date getEpCreateDate() {
		return get("epCreateDate");
	}

	public M setEpCustom(java.lang.String epCustom) {
		set("epCustom", epCustom);
		return (M)this;
	}
	
	public java.lang.String getEpCustom() {
		return getStr("epCustom");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

}
