package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseThinkReportModel<M extends BaseThinkReportModel<M>> extends Model<M> implements IBean {

	public M setTrId(java.lang.String trId) {
		set("trId", trId);
		return (M)this;
	}
	
	public java.lang.String getTrId() {
		return getStr("trId");
	}

	public M setTrName(java.lang.String trName) {
		set("trName", trName);
		return (M)this;
	}
	
	public java.lang.String getTrName() {
		return getStr("trName");
	}

	public M setTrTitle(java.lang.String trTitle) {
		set("trTitle", trTitle);
		return (M)this;
	}
	
	public java.lang.String getTrTitle() {
		return getStr("trTitle");
	}

	public M setTrContent(java.lang.String trContent) {
		set("trContent", trContent);
		return (M)this;
	}
	
	public java.lang.String getTrContent() {
		return getStr("trContent");
	}

	public M setTrResult(java.lang.String trResult) {
		set("trResult", trResult);
		return (M)this;
	}
	
	public java.lang.String getTrResult() {
		return getStr("trResult");
	}

	public M setTrState(java.lang.String trState) {
		set("trState", trState);
		return (M)this;
	}
	
	public java.lang.String getTrState() {
		return getStr("trState");
	}

	public M setTrDieDate(java.lang.String trDieDate) {
		set("trDieDate", trDieDate);
		return (M)this;
	}
	
	public java.lang.String getTrDieDate() {
		return getStr("trDieDate");
	}

	public M setTrDate(java.lang.String trDate) {
		set("trDate", trDate);
		return (M)this;
	}
	
	public java.lang.String getTrDate() {
		return getStr("trDate");
	}

	public M setTrFile(java.lang.String trFile) {
		set("trFile", trFile);
		return (M)this;
	}
	
	public java.lang.String getTrFile() {
		return getStr("trFile");
	}

	public M setEpId(java.lang.String epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.String getEpId() {
		return getStr("epId");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

}
