package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMindTestModel<M extends BaseMindTestModel<M>> extends Model<M> implements IBean {

	public M setMtId(java.lang.String mtId) {
		set("mtId", mtId);
		return (M)this;
	}
	
	public java.lang.String getMtId() {
		return getStr("mtId");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

	public M setMtName(java.lang.String mtName) {
		set("mtName", mtName);
		return (M)this;
	}
	
	public java.lang.String getMtName() {
		return getStr("mtName");
	}

	public M setMtCreateDate(java.util.Date mtCreateDate) {
		set("mtCreateDate", mtCreateDate);
		return (M)this;
	}
	
	public java.util.Date getMtCreateDate() {
		return get("mtCreateDate");
	}

	public M setMtType(java.lang.String mtType) {
		set("mtType", mtType);
		return (M)this;
	}
	
	public java.lang.String getMtType() {
		return getStr("mtType");
	}

	public M setMtDesc(java.lang.String mtDesc) {
		set("mtDesc", mtDesc);
		return (M)this;
	}
	
	public java.lang.String getMtDesc() {
		return getStr("mtDesc");
	}

	public M setMtScore(java.lang.String mtScore) {
		set("mtScore", mtScore);
		return (M)this;
	}
	
	public java.lang.String getMtScore() {
		return getStr("mtScore");
	}

}
