package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserCaseModel<M extends BaseUserCaseModel<M>> extends Model<M> implements IBean {

	public M setUcId(java.lang.String ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.String getUcId() {
		return getStr("ucId");
	}

	public M setUcAccid(java.lang.String ucAccid) {
		set("ucAccid", ucAccid);
		return (M)this;
	}
	
	public java.lang.String getUcAccid() {
		return getStr("ucAccid");
	}

	public M setUcName(java.lang.String ucName) {
		set("ucName", ucName);
		return (M)this;
	}
	
	public java.lang.String getUcName() {
		return getStr("ucName");
	}

	public M setUcPassword(java.lang.String ucPassword) {
		set("ucPassword", ucPassword);
		return (M)this;
	}
	
	public java.lang.String getUcPassword() {
		return getStr("ucPassword");
	}

	public M setUcPhone(java.lang.String ucPhone) {
		set("ucPhone", ucPhone);
		return (M)this;
	}
	
	public java.lang.String getUcPhone() {
		return getStr("ucPhone");
	}

	public M setUcToken(java.lang.String ucToken) {
		set("ucToken", ucToken);
		return (M)this;
	}
	
	public java.lang.String getUcToken() {
		return getStr("ucToken");
	}

	public M setUcCustom(java.lang.String ucCustom) {
		set("ucCustom", ucCustom);
		return (M)this;
	}
	
	public java.lang.String getUcCustom() {
		return getStr("ucCustom");
	}

	public M setUcRole(java.lang.String ucRole) {
		set("ucRole", ucRole);
		return (M)this;
	}
	
	public java.lang.String getUcRole() {
		return getStr("ucRole");
	}

	public M setUcOpenId(java.lang.String ucOpenId) {
		set("ucOpenId", ucOpenId);
		return (M)this;
	}
	
	public java.lang.String getUcOpenId() {
		return getStr("ucOpenId");
	}

}
