package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOpinionRecordModel<M extends BaseOpinionRecordModel<M>> extends Model<M> implements IBean {

	public M setOrId(java.lang.String orId) {
		set("orId", orId);
		return (M)this;
	}
	
	public java.lang.String getOrId() {
		return getStr("orId");
	}

	public M setOrName(java.lang.String orName) {
		set("orName", orName);
		return (M)this;
	}
	
	public java.lang.String getOrName() {
		return getStr("orName");
	}

	public M setOrLeader(java.lang.String orLeader) {
		set("orLeader", orLeader);
		return (M)this;
	}
	
	public java.lang.String getOrLeader() {
		return getStr("orLeader");
	}

	public M setOrReciver(java.lang.String orReciver) {
		set("orReciver", orReciver);
		return (M)this;
	}
	
	public java.lang.String getOrReciver() {
		return getStr("orReciver");
	}

	public M setOrCreateDate(java.util.Date orCreateDate) {
		set("orCreateDate", orCreateDate);
		return (M)this;
	}
	
	public java.util.Date getOrCreateDate() {
		return get("orCreateDate");
	}

	public M setOrContent(java.lang.String orContent) {
		set("orContent", orContent);
		return (M)this;
	}
	
	public java.lang.String getOrContent() {
		return getStr("orContent");
	}

	public M setOrResult(java.lang.String orResult) {
		set("orResult", orResult);
		return (M)this;
	}
	
	public java.lang.String getOrResult() {
		return getStr("orResult");
	}

	public M setOrCustom(java.lang.String orCustom) {
		set("orCustom", orCustom);
		return (M)this;
	}
	
	public java.lang.String getOrCustom() {
		return getStr("orCustom");
	}

}
