package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseCaseReadModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CaseReadModel extends BaseCaseReadModel<CaseReadModel> {
	
}
