package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseCommunityServiceModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommunityServiceModel extends BaseCommunityServiceModel<CommunityServiceModel> {
	
}
