package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseEduplanTaskModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduplanTaskModel extends BaseEduplanTaskModel<EduplanTaskModel> {
	
}
