package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseLawStudyModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LawStudyModel extends BaseLawStudyModel<LawStudyModel> {
	
}
