package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMindTestQstModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MindTestQstModel extends BaseMindTestQstModel<MindTestQstModel> {
	
}
