package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMovieWatchModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MovieWatchModel extends BaseMovieWatchModel<MovieWatchModel> {
	
}
