package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseOpinionRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpinionRecordModel extends BaseOpinionRecordModel<OpinionRecordModel> {
	
}
