package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseTalkEducationModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TalkEducationModel extends BaseTalkEducationModel<TalkEducationModel> {
	
}
