package com.weixin.wj.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dede_diyform2", "id", DedeDiyform2.class);
		arp.addMapping("hae_menu", "mId", Menu.class);
		arp.addMapping("hae_mindtestqst", "mtqId", Mindtestqst.class);
		arp.addMapping("hae_sheet", "SheetName", Sheet.class);
		arp.addMapping("hae_usercase", "ucId", Usercase.class);
		arp.addMapping("hae_userrecord", "urId", Userrecord.class);
		arp.addMapping("test", "id", Test.class);
	}
}

