package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseArchiveRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArchiveRecordModel extends BaseArchiveRecordModel<ArchiveRecordModel> {
	
}
