package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseDailyCheckInModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DailyCheckInModel extends BaseDailyCheckInModel<DailyCheckInModel> {
	
}
