package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseDedeDiyform2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DedeDiyform2 extends BaseDedeDiyform2<DedeDiyform2> {
	
}
