package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseEduplanModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduplanModel extends BaseEduplanModel<EduplanModel> {
	
}
