package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseFeedbackRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FeedbackRecordModel extends BaseFeedbackRecordModel<FeedbackRecordModel> {
	
}
