package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseFoulRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoulRecordModel extends BaseFoulRecordModel<FoulRecordModel> {
	
}
