package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseFrrdbackRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FrrdbackRecordModel extends BaseFrrdbackRecordModel<FrrdbackRecordModel> {
	
}
