package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseInterviewRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterviewRecordModel extends BaseInterviewRecordModel<InterviewRecordModel> {
	
}
