package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseInvOptionModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvOptionModel extends BaseInvOptionModel<InvOptionModel> {
	
}
