package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseLabourEducationModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LabourEducationModel extends BaseLabourEducationModel<LabourEducationModel> {
	
}
