package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseLeaveRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaveRecordModel extends BaseLeaveRecordModel<LeaveRecordModel> {
	
}
