package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMenuModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuModel extends BaseMenuModel<MenuModel> {
	
}
