package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMindTestModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MindTestModel extends BaseMindTestModel<MindTestModel> {
	
}
