package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMindLeadModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MindLeadModel extends BaseMindLeadModel<MindLeadModel> {
	
}
