package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseMindtestqst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mindtestqst extends BaseMindtestqst<Mindtestqst> {
	
}
