package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseResultRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResultRecordModel extends BaseResultRecordModel<ResultRecordModel> {
	
}
