package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseRevisitModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RevisitModel extends BaseRevisitModel<RevisitModel> {
	
}
