package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseRewardPunishModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RewardPunishModel extends BaseRewardPunishModel<RewardPunishModel> {
	
}
