package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseRiskModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RiskModel extends BaseRiskModel<RiskModel> {
	
}
