package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseTaskListModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskListModel extends BaseTaskListModel<TaskListModel> {
	
}
