package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseThinkReportModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThinkReportModel extends BaseThinkReportModel<ThinkReportModel> {
	
}
