package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseUserrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userrecord extends BaseUserrecord<Userrecord> {
	
}
