package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseUserRecordModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRecordModel extends BaseUserRecordModel<UserRecordModel> {
	
}
