package com.weixin.wj.model;

import com.weixin.wj.model.base.BaseUserCaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCaseModel extends BaseUserCaseModel<UserCaseModel> {
	
}
