package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLabourEducationModel<M extends BaseLabourEducationModel<M>> extends Model<M> implements IBean {

	public M setLeId(java.lang.Integer leId) {
		set("leId", leId);
		return (M)this;
	}
	
	public java.lang.Integer getLeId() {
		return getInt("leId");
	}

	public M setLeHelper(java.lang.String leHelper) {
		set("leHelper", leHelper);
		return (M)this;
	}
	
	public java.lang.String getLeHelper() {
		return getStr("leHelper");
	}

	public M setLeDate(java.util.Date leDate) {
		set("leDate", leDate);
		return (M)this;
	}
	
	public java.util.Date getLeDate() {
		return get("leDate");
	}

	public M setLeReason(java.lang.String leReason) {
		set("leReason", leReason);
		return (M)this;
	}
	
	public java.lang.String getLeReason() {
		return getStr("leReason");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

	public M setLePlace(java.lang.String lePlace) {
		set("lePlace", lePlace);
		return (M)this;
	}
	
	public java.lang.String getLePlace() {
		return getStr("lePlace");
	}

}
