package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserRecordModel<M extends BaseUserRecordModel<M>> extends Model<M> implements IBean {

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

	public M setUcId(java.lang.String ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.String getUcId() {
		return getStr("ucId");
	}

	public M setUrName(java.lang.String urName) {
		set("urName", urName);
		return (M)this;
	}
	
	public java.lang.String getUrName() {
		return getStr("urName");
	}

	public M setUrAge(java.lang.Integer urAge) {
		set("urAge", urAge);
		return (M)this;
	}
	
	public java.lang.Integer getUrAge() {
		return getInt("urAge");
	}

	public M setUrAddress(java.lang.String urAddress) {
		set("urAddress", urAddress);
		return (M)this;
	}
	
	public java.lang.String getUrAddress() {
		return getStr("urAddress");
	}

	public M setUrRelationId(java.lang.String urRelationId) {
		set("urRelationId", urRelationId);
		return (M)this;
	}
	
	public java.lang.String getUrRelationId() {
		return getStr("urRelationId");
	}

	public M setUrPortraitUrl(java.lang.String urPortraitUrl) {
		set("urPortraitUrl", urPortraitUrl);
		return (M)this;
	}
	
	public java.lang.String getUrPortraitUrl() {
		return getStr("urPortraitUrl");
	}

	public M setUrSex(java.lang.String urSex) {
		set("urSex", urSex);
		return (M)this;
	}
	
	public java.lang.String getUrSex() {
		return getStr("urSex");
	}

	public M setUrCustom(java.lang.String urCustom) {
		set("urCustom", urCustom);
		return (M)this;
	}
	
	public java.lang.String getUrCustom() {
		return getStr("urCustom");
	}

	public M setUrState(java.lang.String urState) {
		set("urState", urState);
		return (M)this;
	}
	
	public java.lang.String getUrState() {
		return getStr("urState");
	}

	public M setUrResult(java.lang.String urResult) {
		set("urResult", urResult);
		return (M)this;
	}
	
	public java.lang.String getUrResult() {
		return getStr("urResult");
	}

}
