package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTalkEducationModel<M extends BaseTalkEducationModel<M>> extends Model<M> implements IBean {

	public M setTeId(java.lang.String teId) {
		set("teId", teId);
		return (M)this;
	}
	
	public java.lang.String getTeId() {
		return getStr("teId");
	}

	public M setTeName(java.lang.String teName) {
		set("teName", teName);
		return (M)this;
	}
	
	public java.lang.String getTeName() {
		return getStr("teName");
	}

	public M setTeLeader(java.lang.String teLeader) {
		set("teLeader", teLeader);
		return (M)this;
	}
	
	public java.lang.String getTeLeader() {
		return getStr("teLeader");
	}

	public M setTeReciver(java.lang.String teReciver) {
		set("teReciver", teReciver);
		return (M)this;
	}
	
	public java.lang.String getTeReciver() {
		return getStr("teReciver");
	}

	public M setTeCreateDate(java.util.Date teCreateDate) {
		set("teCreateDate", teCreateDate);
		return (M)this;
	}
	
	public java.util.Date getTeCreateDate() {
		return get("teCreateDate");
	}

	public M setTeState(java.lang.String teState) {
		set("teState", teState);
		return (M)this;
	}
	
	public java.lang.String getTeState() {
		return getStr("teState");
	}

	public M setTeContent(java.lang.String teContent) {
		set("teContent", teContent);
		return (M)this;
	}
	
	public java.lang.String getTeContent() {
		return getStr("teContent");
	}

	public M setTeResult(java.lang.String teResult) {
		set("teResult", teResult);
		return (M)this;
	}
	
	public java.lang.String getTeResult() {
		return getStr("teResult");
	}

	public M setTeCustom(java.lang.String teCustom) {
		set("teCustom", teCustom);
		return (M)this;
	}
	
	public java.lang.String getTeCustom() {
		return getStr("teCustom");
	}

}
