package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArchiveRecordModel<M extends BaseArchiveRecordModel<M>> extends Model<M> implements IBean {

	public M setUrId(java.lang.Integer urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.Integer getUrId() {
		return getInt("urId");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

	public M setUrName(java.lang.String urName) {
		set("urName", urName);
		return (M)this;
	}
	
	public java.lang.String getUrName() {
		return getStr("urName");
	}

	public M setUrAge(java.lang.Integer urAge) {
		set("urAge", urAge);
		return (M)this;
	}
	
	public java.lang.Integer getUrAge() {
		return getInt("urAge");
	}

	public M setUrAddress(java.lang.String urAddress) {
		set("urAddress", urAddress);
		return (M)this;
	}
	
	public java.lang.String getUrAddress() {
		return getStr("urAddress");
	}

	public M setUrRelationId(java.lang.Integer urRelationId) {
		set("urRelationId", urRelationId);
		return (M)this;
	}
	
	public java.lang.Integer getUrRelationId() {
		return getInt("urRelationId");
	}

	public M setUrPortraitUrl(java.lang.String urPortraitUrl) {
		set("urPortraitUrl", urPortraitUrl);
		return (M)this;
	}
	
	public java.lang.String getUrPortraitUrl() {
		return getStr("urPortraitUrl");
	}

	public M setUrSex(java.lang.String urSex) {
		set("urSex", urSex);
		return (M)this;
	}
	
	public java.lang.String getUrSex() {
		return getStr("urSex");
	}

	public M setUrCustom(java.lang.String urCustom) {
		set("urCustom", urCustom);
		return (M)this;
	}
	
	public java.lang.String getUrCustom() {
		return getStr("urCustom");
	}

}
