package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDedeDiyform2<M extends BaseDedeDiyform2<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setIfcheck(java.lang.Boolean ifcheck) {
		set("ifcheck", ifcheck);
		return (M)this;
	}
	
	public java.lang.Boolean getIfcheck() {
		return get("ifcheck");
	}

	public M setStart(java.lang.String start) {
		set("start", start);
		return (M)this;
	}
	
	public java.lang.String getStart() {
		return getStr("start");
	}

	public M setEnd(java.lang.String end) {
		set("end", end);
		return (M)this;
	}
	
	public java.lang.String getEnd() {
		return getStr("end");
	}

	public M setPrice(java.lang.String price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.String getPrice() {
		return getStr("price");
	}

	public M setTimes(java.lang.String times) {
		set("times", times);
		return (M)this;
	}
	
	public java.lang.String getTimes() {
		return getStr("times");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
