package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTalkEducationModel<M extends BaseTalkEducationModel<M>> extends Model<M> implements IBean {

	public M setTeId(java.lang.String teId) {
		set("teId", teId);
		return (M)this;
	}
	
	public java.lang.String getTeId() {
		return getStr("teId");
	}

	public M setTeName(java.lang.String teName) {
		set("teName", teName);
		return (M)this;
	}
	
	public java.lang.String getTeName() {
		return getStr("teName");
	}

	public M setTeLeader(java.lang.String teLeader) {
		set("teLeader", teLeader);
		return (M)this;
	}
	
	public java.lang.String getTeLeader() {
		return getStr("teLeader");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

	public M setTeDate(java.util.Date teDate) {
		set("teDate", teDate);
		return (M)this;
	}
	
	public java.util.Date getTeDate() {
		return get("teDate");
	}

	public M setTeState(java.lang.String teState) {
		set("teState", teState);
		return (M)this;
	}
	
	public java.lang.String getTeState() {
		return getStr("teState");
	}

	public M setTeContent(java.lang.String teContent) {
		set("teContent", teContent);
		return (M)this;
	}
	
	public java.lang.String getTeContent() {
		return getStr("teContent");
	}

	public M setTeResult(java.lang.String teResult) {
		set("teResult", teResult);
		return (M)this;
	}
	
	public java.lang.String getTeResult() {
		return getStr("teResult");
	}

	public M setTeFile(java.lang.String teFile) {
		set("teFile", teFile);
		return (M)this;
	}
	
	public java.lang.String getTeFile() {
		return getStr("teFile");
	}

	public M setEpId(java.lang.String epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.String getEpId() {
		return getStr("epId");
	}

	public M setTeCustom(java.lang.String teCustom) {
		set("teCustom", teCustom);
		return (M)this;
	}
	
	public java.lang.String getTeCustom() {
		return getStr("teCustom");
	}

}
