package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRevisitModel<M extends BaseRevisitModel<M>> extends Model<M> implements IBean {

	public M setRvId(java.lang.Integer rvId) {
		set("rvId", rvId);
		return (M)this;
	}
	
	public java.lang.Integer getRvId() {
		return getInt("rvId");
	}

	public M setRvName(java.lang.String rvName) {
		set("rvName", rvName);
		return (M)this;
	}
	
	public java.lang.String getRvName() {
		return getStr("rvName");
	}

	public M setRvTitle(java.lang.String rvTitle) {
		set("rvTitle", rvTitle);
		return (M)this;
	}
	
	public java.lang.String getRvTitle() {
		return getStr("rvTitle");
	}

	public M setRvCreateDate(java.util.Date rvCreateDate) {
		set("rvCreateDate", rvCreateDate);
		return (M)this;
	}
	
	public java.util.Date getRvCreateDate() {
		return get("rvCreateDate");
	}

	public M setRvContent(java.lang.String rvContent) {
		set("rvContent", rvContent);
		return (M)this;
	}
	
	public java.lang.String getRvContent() {
		return getStr("rvContent");
	}

	public M setRvReciver(java.lang.String rvReciver) {
		set("rvReciver", rvReciver);
		return (M)this;
	}
	
	public java.lang.String getRvReciver() {
		return getStr("rvReciver");
	}

	public M setRvResult(java.lang.String rvResult) {
		set("rvResult", rvResult);
		return (M)this;
	}
	
	public java.lang.String getRvResult() {
		return getStr("rvResult");
	}

	public M setRvCustom(java.lang.String rvCustom) {
		set("rvCustom", rvCustom);
		return (M)this;
	}
	
	public java.lang.String getRvCustom() {
		return getStr("rvCustom");
	}

}
