package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSheet<M extends BaseSheet<M>> extends Model<M> implements IBean {

	public M setSheetName(java.lang.String SheetName) {
		set("SheetName", SheetName);
		return (M)this;
	}
	
	public java.lang.String getSheetName() {
		return getStr("SheetName");
	}

	public M setChinese(java.lang.String Chinese) {
		set("Chinese", Chinese);
		return (M)this;
	}
	
	public java.lang.String getChinese() {
		return getStr("Chinese");
	}

}
