package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaveRecordModel<M extends BaseLeaveRecordModel<M>> extends Model<M> implements IBean {

	public M setReId(java.lang.Integer reId) {
		set("reId", reId);
		return (M)this;
	}
	
	public java.lang.Integer getReId() {
		return getInt("reId");
	}

	public M setReUsername(java.lang.String reUsername) {
		set("reUsername", reUsername);
		return (M)this;
	}
	
	public java.lang.String getReUsername() {
		return getStr("reUsername");
	}

	public M setReHelper(java.lang.String reHelper) {
		set("reHelper", reHelper);
		return (M)this;
	}
	
	public java.lang.String getReHelper() {
		return getStr("reHelper");
	}

	public M setReReason(java.lang.String reReason) {
		set("reReason", reReason);
		return (M)this;
	}
	
	public java.lang.String getReReason() {
		return getStr("reReason");
	}

	public M setReDate(java.util.Date reDate) {
		set("reDate", reDate);
		return (M)this;
	}
	
	public java.util.Date getReDate() {
		return get("reDate");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

}
