package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDailyCheckInModel<M extends BaseDailyCheckInModel<M>> extends Model<M> implements IBean {

	public M setDiId(java.lang.Integer diId) {
		set("diId", diId);
		return (M)this;
	}
	
	public java.lang.Integer getDiId() {
		return getInt("diId");
	}

	public M setDiName(java.lang.String diName) {
		set("diName", diName);
		return (M)this;
	}
	
	public java.lang.String getDiName() {
		return getStr("diName");
	}

	public M setDiLeader(java.lang.Integer diLeader) {
		set("diLeader", diLeader);
		return (M)this;
	}
	
	public java.lang.Integer getDiLeader() {
		return getInt("diLeader");
	}

	public M setDiReciver(java.lang.Integer diReciver) {
		set("diReciver", diReciver);
		return (M)this;
	}
	
	public java.lang.Integer getDiReciver() {
		return getInt("diReciver");
	}

	public M setDiCreateDate(java.util.Date diCreateDate) {
		set("diCreateDate", diCreateDate);
		return (M)this;
	}
	
	public java.util.Date getDiCreateDate() {
		return get("diCreateDate");
	}

	public M setDiTime(java.util.Date diTime) {
		set("diTime", diTime);
		return (M)this;
	}
	
	public java.util.Date getDiTime() {
		return get("diTime");
	}

	public M setDiState(java.lang.String diState) {
		set("diState", diState);
		return (M)this;
	}
	
	public java.lang.String getDiState() {
		return getStr("diState");
	}

	public M setDiResult(java.lang.String diResult) {
		set("diResult", diResult);
		return (M)this;
	}
	
	public java.lang.String getDiResult() {
		return getStr("diResult");
	}

	public M setDiCustom(java.lang.String diCustom) {
		set("diCustom", diCustom);
		return (M)this;
	}
	
	public java.lang.String getDiCustom() {
		return getStr("diCustom");
	}

}
