package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMindTestQstModel<M extends BaseMindTestQstModel<M>> extends Model<M> implements IBean {

	public M setMtqId(java.lang.Integer mtqId) {
		set("mtqId", mtqId);
		return (M)this;
	}
	
	public java.lang.Integer getMtqId() {
		return getInt("mtqId");
	}

	public M setMtqType(java.lang.Integer mtqType) {
		set("mtqType", mtqType);
		return (M)this;
	}
	
	public java.lang.Integer getMtqType() {
		return getInt("mtqType");
	}

	public M setMtqTitle(java.lang.String mtqTitle) {
		set("mtqTitle", mtqTitle);
		return (M)this;
	}
	
	public java.lang.String getMtqTitle() {
		return getStr("mtqTitle");
	}

	public M setMtqOP1(java.lang.String mtqOP1) {
		set("mtqOP1", mtqOP1);
		return (M)this;
	}
	
	public java.lang.String getMtqOP1() {
		return getStr("mtqOP1");
	}

	public M setMtqOP2(java.lang.String mtqOP2) {
		set("mtqOP2", mtqOP2);
		return (M)this;
	}
	
	public java.lang.String getMtqOP2() {
		return getStr("mtqOP2");
	}

	public M setMtqOP3(java.lang.String mtqOP3) {
		set("mtqOP3", mtqOP3);
		return (M)this;
	}
	
	public java.lang.String getMtqOP3() {
		return getStr("mtqOP3");
	}

	public M setMtqOP4(java.lang.String mtqOP4) {
		set("mtqOP4", mtqOP4);
		return (M)this;
	}
	
	public java.lang.String getMtqOP4() {
		return getStr("mtqOP4");
	}

	public M setMtqAnsw(java.lang.String mtqAnsw) {
		set("mtqAnsw", mtqAnsw);
		return (M)this;
	}
	
	public java.lang.String getMtqAnsw() {
		return getStr("mtqAnsw");
	}

	public M setMtqCustom(java.lang.String mtqCustom) {
		set("mtqCustom", mtqCustom);
		return (M)this;
	}
	
	public java.lang.String getMtqCustom() {
		return getStr("mtqCustom");
	}

}
