package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResultRecordModel<M extends BaseResultRecordModel<M>> extends Model<M> implements IBean {

	public M setReId(java.lang.Integer reId) {
		set("reId", reId);
		return (M)this;
	}
	
	public java.lang.Integer getReId() {
		return getInt("reId");
	}

	public M setReDayInOut(java.lang.String reDayInOut) {
		set("reDayInOut", reDayInOut);
		return (M)this;
	}
	
	public java.lang.String getReDayInOut() {
		return getStr("reDayInOut");
	}

	public M setReInterView(java.lang.String reInterView) {
		set("reInterView", reInterView);
		return (M)this;
	}
	
	public java.lang.String getReInterView() {
		return getStr("reInterView");
	}

	public M setReWorkEducation(java.lang.String reWorkEducation) {
		set("reWorkEducation", reWorkEducation);
		return (M)this;
	}
	
	public java.lang.String getReWorkEducation() {
		return getStr("reWorkEducation");
	}

	public M setReTalkEducation(java.lang.String reTalkEducation) {
		set("reTalkEducation", reTalkEducation);
		return (M)this;
	}
	
	public java.lang.String getReTalkEducation() {
		return getStr("reTalkEducation");
	}

	public M setReFoulRecord(java.lang.String reFoulRecord) {
		set("reFoulRecord", reFoulRecord);
		return (M)this;
	}
	
	public java.lang.String getReFoulRecord() {
		return getStr("reFoulRecord");
	}

	public M setReCommunity(java.lang.String reCommunity) {
		set("reCommunity", reCommunity);
		return (M)this;
	}
	
	public java.lang.String getReCommunity() {
		return getStr("reCommunity");
	}

	public M setReOpinion(java.lang.String reOpinion) {
		set("reOpinion", reOpinion);
		return (M)this;
	}
	
	public java.lang.String getReOpinion() {
		return getStr("reOpinion");
	}

	public M setReDate(java.util.Date reDate) {
		set("reDate", reDate);
		return (M)this;
	}
	
	public java.util.Date getReDate() {
		return get("reDate");
	}

	public M setReDay(java.lang.String reDay) {
		set("reDay", reDay);
		return (M)this;
	}
	
	public java.lang.String getReDay() {
		return getStr("reDay");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

	public M setReResult(java.lang.String reResult) {
		set("reResult", reResult);
		return (M)this;
	}
	
	public java.lang.String getReResult() {
		return getStr("reResult");
	}

}
