package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEduplanModel<M extends BaseEduplanModel<M>> extends Model<M> implements IBean {

	public M setEpId(java.lang.Integer epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.Integer getEpId() {
		return getInt("epId");
	}

	public M setEpName(java.lang.String epName) {
		set("epName", epName);
		return (M)this;
	}
	
	public java.lang.String getEpName() {
		return getStr("epName");
	}

	public M setEpTitle(java.lang.String epTitle) {
		set("epTitle", epTitle);
		return (M)this;
	}
	
	public java.lang.String getEpTitle() {
		return getStr("epTitle");
	}

	public M setEpContinuing(java.lang.String epContinuing) {
		set("epContinuing", epContinuing);
		return (M)this;
	}
	
	public java.lang.String getEpContinuing() {
		return getStr("epContinuing");
	}

	public M setEpContent(java.lang.String epContent) {
		set("epContent", epContent);
		return (M)this;
	}
	
	public java.lang.String getEpContent() {
		return getStr("epContent");
	}

	public M setEpCreateDate(java.util.Date epCreateDate) {
		set("epCreateDate", epCreateDate);
		return (M)this;
	}
	
	public java.util.Date getEpCreateDate() {
		return get("epCreateDate");
	}

	public M setEpCustom(java.lang.String epCustom) {
		set("epCustom", epCustom);
		return (M)this;
	}
	
	public java.lang.String getEpCustom() {
		return getStr("epCustom");
	}

}
