package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRiskModel<M extends BaseRiskModel<M>> extends Model<M> implements IBean {

	public M setRkId(java.lang.Integer rkId) {
		set("rkId", rkId);
		return (M)this;
	}
	
	public java.lang.Integer getRkId() {
		return getInt("rkId");
	}

	public M setRkName(java.lang.String rkName) {
		set("rkName", rkName);
		return (M)this;
	}
	
	public java.lang.String getRkName() {
		return getStr("rkName");
	}

	public M setRkTitle(java.lang.String rkTitle) {
		set("rkTitle", rkTitle);
		return (M)this;
	}
	
	public java.lang.String getRkTitle() {
		return getStr("rkTitle");
	}

	public M setRkContent(java.lang.String rkContent) {
		set("rkContent", rkContent);
		return (M)this;
	}
	
	public java.lang.String getRkContent() {
		return getStr("rkContent");
	}

	public M setRkDate(java.util.Date rkDate) {
		set("rkDate", rkDate);
		return (M)this;
	}
	
	public java.util.Date getRkDate() {
		return get("rkDate");
	}

	public M setRkReciver(java.lang.String rkReciver) {
		set("rkReciver", rkReciver);
		return (M)this;
	}
	
	public java.lang.String getRkReciver() {
		return getStr("rkReciver");
	}

	public M setRkEvaluator(java.lang.String rkEvaluator) {
		set("rkEvaluator", rkEvaluator);
		return (M)this;
	}
	
	public java.lang.String getRkEvaluator() {
		return getStr("rkEvaluator");
	}

	public M setRkResult(java.lang.String rkResult) {
		set("rkResult", rkResult);
		return (M)this;
	}
	
	public java.lang.String getRkResult() {
		return getStr("rkResult");
	}

	public M setRkCustom(java.lang.String rkCustom) {
		set("rkCustom", rkCustom);
		return (M)this;
	}
	
	public java.lang.String getRkCustom() {
		return getStr("rkCustom");
	}

}
