package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaveRecordModel<M extends BaseLeaveRecordModel<M>> extends Model<M> implements IBean {

	public M setLrId(java.lang.String lrId) {
		set("lrId", lrId);
		return (M)this;
	}
	
	public java.lang.String getLrId() {
		return getStr("lrId");
	}

	public M setLrName(java.lang.String lrName) {
		set("lrName", lrName);
		return (M)this;
	}
	
	public java.lang.String getLrName() {
		return getStr("lrName");
	}

	public M setLrLeader(java.lang.String lrLeader) {
		set("lrLeader", lrLeader);
		return (M)this;
	}
	
	public java.lang.String getLrLeader() {
		return getStr("lrLeader");
	}

	public M setLrReciver(java.lang.String lrReciver) {
		set("lrReciver", lrReciver);
		return (M)this;
	}
	
	public java.lang.String getLrReciver() {
		return getStr("lrReciver");
	}

	public M setLrCreateDate(java.util.Date lrCreateDate) {
		set("lrCreateDate", lrCreateDate);
		return (M)this;
	}
	
	public java.util.Date getLrCreateDate() {
		return get("lrCreateDate");
	}

	public M setLrContent(java.lang.String lrContent) {
		set("lrContent", lrContent);
		return (M)this;
	}
	
	public java.lang.String getLrContent() {
		return getStr("lrContent");
	}

	public M setLrResult(java.lang.String lrResult) {
		set("lrResult", lrResult);
		return (M)this;
	}
	
	public java.lang.String getLrResult() {
		return getStr("lrResult");
	}

	public M setLrCustom(java.lang.String lrCustom) {
		set("lrCustom", lrCustom);
		return (M)this;
	}
	
	public java.lang.String getLrCustom() {
		return getStr("lrCustom");
	}

}
