package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskListModel<M extends BaseTaskListModel<M>> extends Model<M> implements IBean {

	public M setTlId(java.lang.String tlId) {
		set("tlId", tlId);
		return (M)this;
	}
	
	public java.lang.String getTlId() {
		return getStr("tlId");
	}

	public M setTlName(java.lang.String tlName) {
		set("tlName", tlName);
		return (M)this;
	}
	
	public java.lang.String getTlName() {
		return getStr("tlName");
	}

	public M setTlTitle(java.lang.String tlTitle) {
		set("tlTitle", tlTitle);
		return (M)this;
	}
	
	public java.lang.String getTlTitle() {
		return getStr("tlTitle");
	}

	public M setTlContent(java.lang.String tlContent) {
		set("tlContent", tlContent);
		return (M)this;
	}
	
	public java.lang.String getTlContent() {
		return getStr("tlContent");
	}

	public M setTlDate(java.util.Date tlDate) {
		set("tlDate", tlDate);
		return (M)this;
	}
	
	public java.util.Date getTlDate() {
		return get("tlDate");
	}

	public M setTlCustom(java.lang.String tlCustom) {
		set("tlCustom", tlCustom);
		return (M)this;
	}
	
	public java.lang.String getTlCustom() {
		return getStr("tlCustom");
	}

}
