package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTalkEducationModel<M extends BaseTalkEducationModel<M>> extends Model<M> implements IBean {

	public M setTeId(java.lang.Integer teId) {
		set("teId", teId);
		return (M)this;
	}
	
	public java.lang.Integer getTeId() {
		return getInt("teId");
	}

	public M setTeHelper(java.lang.String teHelper) {
		set("teHelper", teHelper);
		return (M)this;
	}
	
	public java.lang.String getTeHelper() {
		return getStr("teHelper");
	}

	public M setTeDate(java.util.Date teDate) {
		set("teDate", teDate);
		return (M)this;
	}
	
	public java.util.Date getTeDate() {
		return get("teDate");
	}

	public M setTeReason(java.lang.String teReason) {
		set("teReason", teReason);
		return (M)this;
	}
	
	public java.lang.String getTeReason() {
		return getStr("teReason");
	}

}
