package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenuModel<M extends BaseMenuModel<M>> extends Model<M> implements IBean {

	public M setMId(java.lang.Integer mId) {
		set("mId", mId);
		return (M)this;
	}
	
	public java.lang.Integer getMId() {
		return getInt("mId");
	}

	public M setMParentId(java.lang.Integer mParentId) {
		set("mParentId", mParentId);
		return (M)this;
	}
	
	public java.lang.Integer getMParentId() {
		return getInt("mParentId");
	}

	public M setMName(java.lang.String mName) {
		set("mName", mName);
		return (M)this;
	}
	
	public java.lang.String getMName() {
		return getStr("mName");
	}

	public M setMFa(java.lang.String mFa) {
		set("mFa", mFa);
		return (M)this;
	}
	
	public java.lang.String getMFa() {
		return getStr("mFa");
	}

	public M setMSrc(java.lang.String mSrc) {
		set("mSrc", mSrc);
		return (M)this;
	}
	
	public java.lang.String getMSrc() {
		return getStr("mSrc");
	}

	public M setMRole(java.lang.String mRole) {
		set("mRole", mRole);
		return (M)this;
	}
	
	public java.lang.String getMRole() {
		return getStr("mRole");
	}

	public M setMOrder(java.lang.Integer mOrder) {
		set("mOrder", mOrder);
		return (M)this;
	}
	
	public java.lang.Integer getMOrder() {
		return getInt("mOrder");
	}

	public M setMCustom(java.lang.String mCustom) {
		set("mCustom", mCustom);
		return (M)this;
	}
	
	public java.lang.String getMCustom() {
		return getStr("mCustom");
	}

}
