package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommunityServiceModel<M extends BaseCommunityServiceModel<M>> extends Model<M> implements IBean {

	public M setCsId(java.lang.Integer csId) {
		set("csId", csId);
		return (M)this;
	}
	
	public java.lang.Integer getCsId() {
		return getInt("csId");
	}

	public M setCsHelper(java.lang.String csHelper) {
		set("csHelper", csHelper);
		return (M)this;
	}
	
	public java.lang.String getCsHelper() {
		return getStr("csHelper");
	}

	public M setCsDate(java.util.Date csDate) {
		set("csDate", csDate);
		return (M)this;
	}
	
	public java.util.Date getCsDate() {
		return get("csDate");
	}

	public M setCsReason(java.lang.String csReason) {
		set("csReason", csReason);
		return (M)this;
	}
	
	public java.lang.String getCsReason() {
		return getStr("csReason");
	}

}
