package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterviewRecordModel<M extends BaseInterviewRecordModel<M>> extends Model<M> implements IBean {

	public M setIrId(java.lang.Integer irId) {
		set("irId", irId);
		return (M)this;
	}
	
	public java.lang.Integer getIrId() {
		return getInt("irId");
	}

	public M setIrHelper(java.lang.String irHelper) {
		set("irHelper", irHelper);
		return (M)this;
	}
	
	public java.lang.String getIrHelper() {
		return getStr("irHelper");
	}

	public M setIrDate(java.util.Date irDate) {
		set("irDate", irDate);
		return (M)this;
	}
	
	public java.util.Date getIrDate() {
		return get("irDate");
	}

	public M setIrReason(java.lang.String irReason) {
		set("irReason", irReason);
		return (M)this;
	}
	
	public java.lang.String getIrReason() {
		return getStr("irReason");
	}

	public M setUcId(java.lang.Integer ucId) {
		set("ucId", ucId);
		return (M)this;
	}
	
	public java.lang.Integer getUcId() {
		return getInt("ucId");
	}

}
