package com.weixin.wj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMovieWatchModel<M extends BaseMovieWatchModel<M>> extends Model<M> implements IBean {

	public M setWmId(java.lang.String wmId) {
		set("wmId", wmId);
		return (M)this;
	}
	
	public java.lang.String getWmId() {
		return getStr("wmId");
	}

	public M setWmName(java.lang.String wmName) {
		set("wmName", wmName);
		return (M)this;
	}
	
	public java.lang.String getWmName() {
		return getStr("wmName");
	}

	public M setWmTitle(java.lang.String wmTitle) {
		set("wmTitle", wmTitle);
		return (M)this;
	}
	
	public java.lang.String getWmTitle() {
		return getStr("wmTitle");
	}

	public M setWmContent(java.lang.String wmContent) {
		set("wmContent", wmContent);
		return (M)this;
	}
	
	public java.lang.String getWmContent() {
		return getStr("wmContent");
	}

	public M setWmResult(java.lang.String wmResult) {
		set("wmResult", wmResult);
		return (M)this;
	}
	
	public java.lang.String getWmResult() {
		return getStr("wmResult");
	}

	public M setWmState(java.lang.String wmState) {
		set("wmState", wmState);
		return (M)this;
	}
	
	public java.lang.String getWmState() {
		return getStr("wmState");
	}

	public M setWmDate(java.util.Date wmDate) {
		set("wmDate", wmDate);
		return (M)this;
	}
	
	public java.util.Date getWmDate() {
		return get("wmDate");
	}

	public M setWmScreen(java.lang.String wmScreen) {
		set("wmScreen", wmScreen);
		return (M)this;
	}
	
	public java.lang.String getWmScreen() {
		return getStr("wmScreen");
	}

	public M setWmReview(java.lang.String wmReview) {
		set("wmReview", wmReview);
		return (M)this;
	}
	
	public java.lang.String getWmReview() {
		return getStr("wmReview");
	}

	public M setEpId(java.lang.String epId) {
		set("epId", epId);
		return (M)this;
	}
	
	public java.lang.String getEpId() {
		return getStr("epId");
	}

	public M setUrId(java.lang.String urId) {
		set("urId", urId);
		return (M)this;
	}
	
	public java.lang.String getUrId() {
		return getStr("urId");
	}

}
